// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
export let contractsToInstances = new Map<string, string>();
contractsToInstances.set('0x0ce22770451a8acad1220d9d1678656b4fae4a1d', // Instance-bsc-0.1
  0.1-bsc
);
// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
