// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
export let contractsToInstances = new Map<string, string>();
contractsToInstances.set(
  '0x84443cfd09a48af6ef360c6976c5392ac5023a1f', // Instance-bnb-0.1
  'bnb-0.1',
);
contractsToInstances.set(
  '0xd47438c816c9e7f2e2888e060936a499af9582b3', // Instance-bnb-1
  'bnb-1',
);
contractsToInstances.set(
  '0x330bdfade01ee9bf63c209ee33102dd334618e0a', // Instance-bnb-10
  'bnb-10',
);
contractsToInstances.set(
  '0x1e34a77868e19a6647b1f2f47b51ed72dede95dd', // Instance-bnb-100
  'bnb-100',
);
contractsToInstances.set(
  '0x992a81fa34aa6ecd9520f39f858abc51fee6994a', // Instance-matic-0.1
  'matic-0.1',
);
contractsToInstances.set(
  '0x12d66f87a04a9e220743712ce6d9bb1b5616b8fc', // Instance-eth-0.1
  'eth-0.1',
);
contractsToInstances.set(
  '0x47ce0c6ed5b0ce3d3a51fdb1c52dc66a7c3c2936', // Instance-eth-1
  'eth-1',
);
contractsToInstances.set(
  '0x910cbd523d972eb0a6f4cae4618ad62622b39dbf', // Instance-eth-10
  'eth-10',
);
contractsToInstances.set(
  '0xa160cdab225685da1d56aa342ad8841c3b53f291', // Instance-eth-100
  'eth-100',
);
// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
