// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
export let contractsToInstances = new Map<string, string>();
contractsToInstances.set("0x84443cfd09a48af6ef360c6976c5392ac5023a1f", // Instance-bnb-0.1
  "bnb-0.1"
);
contractsToInstances.set("0xd47438c816c9e7f2e2888e060936a499af9582b3", // Instance-bnb-1
  "bnb-1"
);
contractsToInstances.set("0x330bdfade01ee9bf63c209ee33102dd334618e0a", // Instance-bnb-10
  "bnb-10"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd", // Instance-bnb-100
  "bnb-100"
);
contractsToInstances.set("0x992a81fa34aa6ecd9520f39f858abc51fee6994a", // Instance-matic-0.1
  "matic-0.1"
);
// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
